work_dir: ./logs/oriented_rcnn_aircraft
experiment: train_oriented_rcnn
load_from: ./checkpoints/pretrained/oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth
angle_version: le90
log_level: INFO

dataset_type: DOTAAircraftDataset
data_root: ./data/DOTA_annotations

defaults:
  - model: oriented_rcnn
  - dataset: dataset
  - augmentations: default_augs
  - optimizer: sgd
  - callbacks: defaults
  - logger: tensorboard
  - trainer: default
  - _self_
